sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: rEsVABcTxQ/5DNciusMg7j1N1xiaSdrEaeV7B+KeirIwoxjx3+ziDOFqsHGf0bdQ5V46VTINY220x8T2E+f8VE9+fWCNjPurb3AhDWMb/M/wmLfHwz+TrhOAXupeWsX4Wlb4hKucmwj8ahGdINRnX1fyIg8WRtOAJUAH5+abvc/k5VxfOmmNPJTtgLPtASwIF45PCq5uu2wY4ZmEyRg8lCxOEDq7D+CPRuUqHVR6L9q2iJIgirMGD547vJKeALbR+6W97WIW4iU16R9mNzHz05oqbyjwPxC4n48FqM0syIzQtxaP+W7s/WCPkzrKygthR6Oro6/X/QM65ITlXK6Xp/z1W4flVCZGn5VsTP4N10EnckC6+bTS+s3EWrLcTqq8c2rflc+q+sv4qsUPEv5Gf7ky0lH+yYoQWLsYsNG2q/Ss1aODTmfpp/W3c7RMbTGzVg1ib8uglbRv0qPn0BUCKeVw4IazL+kuYQtOICl/hxb/JbLb3ky/SWvPkkRZpGWVI27uUi3XE6QwRwlFYOeiXAXGvFWwpRq5ZfNT//7NxqgSF5E2bXF+O4B3uSpYcOBAfAE30pXDhR9LaaSLoII2mry86xyJqGjBPRzz48oeFa1OaW7ya4uq0LvxFV6cdKZVedVrELQ5gR4qPEJSbtCWIUsfeg9/JgkhVi5rpiwQLos=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Queen-of-the-Pirate-Isle_2798
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy